import os
import smtplib

from dotenv import load_dotenv

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

load_dotenv()

EMAIL_ADDRESS = os.getenv("EMAIL_ADDRESS")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
ALERT_EMAIL = os.getenv("ALERT_EMAIL")


def send_email_alert(state):

    subject = f"🚨 AquaSentinel Emergency Alert - {state['village']}"

    body = f"""
AquaSentinel Emergency Water Quality Alert

Village:
{state['village']}

Water Source:
{state['water_source']}

Flood Status:
{state['flood_status']}

Classification:
{state['classification']}

Risk:
{state['risk']}

Priority:
{state['priority']}

Recommendation:
{state['recommendation']}

Please initiate emergency response immediately.

Generated by AquaSentinel.
"""

    message = MIMEMultipart()

    message["From"] = EMAIL_ADDRESS
    message["To"] = ALERT_EMAIL
    message["Subject"] = subject

    message.attach(MIMEText(body, "plain"))

    try:

        with smtplib.SMTP("smtp.gmail.com", 587) as server:

            server.starttls()

            server.login(
                EMAIL_ADDRESS,
                EMAIL_PASSWORD
            )

            server.sendmail(
                EMAIL_ADDRESS,
                ALERT_EMAIL,
                message.as_string()
            )

        print("✓ Email Alert Sent Successfully")

    except Exception as e:

        print("Email Sending Failed")

        print(e)